mirrorfm/data

- youtube-channels.csv
> Add TheLazyLazyMe

- youtube-channels.csv
Added track filters for this here https://github.com/mirrorfm/trackfilter/pull/1
> Add Minitel

- youtube-channels.csv
yugen - a really nice ambient channel by the same guy who runs the slav house channel
> Add yugen.

- youtube-channels.csv
Need to update https://github.com/mirrorfm/trackfilter first
> Add The Electronic Vinyl

- youtube-channels.csv
> [channel] Add Sinchi Collective

- youtube-channels.csv
Hey guys, 
just wanted to have an Analog Advisory Mirror on Spotify too! :)
> [channel] Analog Advisory

- youtube-channels.csv
Didn't find it in the document and thought that this should also be on Spotify!
> Liquid Youth

- youtube-channels.csv
> Future Funk

- youtube-channels.csv
Could you please add this channel too? :)
> [channel] NovaFuture Blog

- discogs-labels.csv
> [label] Gossip Records, DJ International Records

- youtube-channels.csv
Added Maslow Unkown and Funky Unkown very good house channels
> [channel] Maslow Unknown

- youtube-channels.csv
Hello I did like to add a new music channel
> [channel] IndiETrap

- youtube-channels.csv
Added youtube channel Pasti's Library
> [channel] Pasti's Library

- discogs-labels.csv
> [label] Audiophile Live

- youtube-channels.csv
> [channel] The Legendary Uploadzz, Lonho Archive, DistrictBass, Inspector Dubplate, OURGRND, Drum&BassArena, SpinTwistRecords

- youtube-channels.csv
Corrected the links for some of the last update, since the system didn't get them
> [channel] Drum&BassArena, OURGRND

- discogs-labels.csv
- youtube-channels.csv
Moodmusic, Cracki Records, Rhythm Records, Report, Chill Soul and Space, Apivore, MyCandies, Alberto MH, DeepZone, Garage House TV, Track ID, bluntboy, Heavy Skin, Metaforique Radio
> [labels & channels] High Focus, Future Retro London, underground quality

- discogs-labels.csv
- youtube-channels.csv
hanksiedonny, extrafan, AgnosticRhythm, LA Kistoc, Ipomea, Housepedia Music, Dansu Discs, MoBlack Records
> [channels & labels] Hallucigen, Musical Wastelands, sonicmartingale

- discogs-labels.csv
> [label] Mau5trap Recordings

- youtube-channels.csv
> [channel] 17tumba

- youtube-channels.csv
Added "Classic House Music Lover!".
> [channel] Classic House Music Lover!

- youtube-channels.csv
> [channel] postworthymusic

- youtube-channels.csv
Added "2 Phunkee 4 U" and "classycjewel".
> [channel] 2 Phunkee 4 U, classycjewel

- youtube-channels.csv
> [channel] DJ EPhunk

- youtube-channels.csv
WE ADDED OUR YOUTUBE CHANNEL --> 47011 RECORDS IS AN ITALIAN INDEPENDENT PUBLISHER AND THIS IS OUR YOUTUBE CHANNEL https://www.youtube.com/@Records-ug6fq
> [channel] 47011 Records

- youtube-channels.csv
> [Channel] joyaux de la musique

- discogs-labels.csv
> [label] CRMS, Onako Records

- youtube-channels.csv
> [channel] Record Thief
